// Variables que representan el estado del sistema

let state = {
  categoriaVehiculo: null,
  vehiculoActual: [],
  autorizaPesaje: false,
  no_runt: false,
  placa: "XXX000",
  rutaFotoPlaca: "C:/ANPR/fotos_placas",
  clasificacion: "OTROS",
  puertoCamaraPlaca: 9000,
  IpCamaraPlaca: "127.0.0.1",
  puertoCamaraPlacaEstatica: 9001,
  IpCamaraPlacaEstatica: "127.0.0.1",
  ipPeaje: '127.0.0.1',
  puertoPeaje: 3005,
  semafotoIngresoEstacionRojo: false,
  semafotoIngresoEstacionVerde: true,
  semaforoIngresoEstaticaRojo: false,
  semaforoIngresoEstaticaVerde: false,
  semaforoSalidaNacionalRojo: false,
  semaforoSalidaNacionalVerde: false,
  semaforoEstaticaSobrePeso: false,
  estadoBasculaDinamica: false,
  estadoDisplayEstatica: false,
  estadoDisplayIngresoEstacion: false,
  estadoPlc: {},
  numeroVehiculos: 0,
  plcIp: "127.0.0.1",
  plcPort: "9090",
  ipDisplayContelect: "127.0.0.1",
  portDisplayContelect: "5001",
  ipDisplayEstatica: "127.0.0.1",
  portDisplayEstatica: "5002",
  ipDisplayIngresoEstacion: "127.0.0.1",
  portDisplayIngresoEstacion: "5003",
  placaIp: "No",
  rutaPlacaIp: "E:/nueva dinamica/Back/src/placas",
  rutaPlacaProcesada: "E:/nueva dinamica/Back/src/placasProcesadas",
  pesos: {
    A: 0,
    B: 0,
    C: 0,
    D: 0,
  },
  sensores: {
    A: [],
    B: [],
    C: [],
    D: [],
  },
  vehiculoActual: [],
  vehiculosTerminados: [],
  loop: "Apagado",
  caso: 0,

  //display
  enviandoMensajePersonalizado: false,
  ultimoMensaje: null,
  ingresoDinamicaState: '34',
  No_ingresoDinamicaState: '35',
  soloDinamicaState: '33',
  operacionNormalState: 'ns=4;i=14',
  salidaNacionalState: 'ns=4;i=8',
  autorizarPesajeState: '46',
  noRuntState: '54',
  ingresoEstaticaState: '36',
  sobrePesoState: '42',
  soloEstaticaState: '37',
  soloNacionalState: '38',
  automaticoState: '39',
  port: 3005
};

// Exportamos para usarlos en otros módulos
module.exports = {
  state,
};
